name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get version from package.json
  	id: version
  	run: |
    	VERSION=$(node -p "require('./package.json').version")
    	echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/dotnovi:v${{ steps.version.outputs.version }} .
          docker tag ghcr.io/${{ github.repository_owner }}/dotnovi:v${{ steps.version.outputs.version }} ghcr.io/${{ github.repository_owner }}/dotnovi:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/dotnovi:v${{ steps.version.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/dotnovi:latest